# wayle shell --config ~/repo/molnios-shared/config/wayle/config.toml
[bar]
scale = 1


[[bar.layout]]
monitor = "*"
left = ["dashboard"]
center = ["clock"]
right = ["battery", "network", "volume", "systray"]