#!/usr/bin/env bash
# molnios-templates.sh - Template generator for MolniOS color system
# Part of the MolniOS project.
# ==============================================================================
# Generates application-specific config files from pywal color cache.
# Works with any backend (pywal16, wallust, matugen) as long as colors are
# available in ~/.cache/wal/colors.sh
# ==============================================================================

set -euo pipefail

CACHE_DIR="${XDG_CACHE_HOME:-$HOME/.cache}"
CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}"

# Source colors from cache (pywal-compatible format)
COLORS_SH="$CACHE_DIR/wal/colors.sh"
[[ -f "$COLORS_SH" ]] || {
    echo "Error: colors.sh not found at $COLORS_SH" >&2
    exit 1
}

# shellcheck disable=SC1090
source "$COLORS_SH"

# Fallback if colors are in different variables
color0="${color0:-$wal_color0}"
color1="${color1:-$wal_color1}"
color2="${color2:-$wal_color2}"
color3="${color3:-$wal_color3}"
color4="${color4:-$wal_color4}"
color5="${color5:-$wal_color5}"
color6="${color6:-$wal_color6}"
color7="${color7:-$wal_color7}"
color8="${color8:-$wal_color8}"
color9="${color9:-$wal_color9}"
color10="${color10:-$wal_color10}"
color11="${color11:-$wal_color11}"
color12="${color12:-$wal_color12}"
color13="${color13:-$wal_color13}"
color14="${color14:-$wal_color14}"
color15="${color15:-$wal_color15}"

background="${background:-$color0}"
foreground="${foreground:-$color7}"
cursor="${cursor:-$color7}"

# Helper: convert hex to rgba
hex_to_rgba(){
    local hex="$1"
    local alpha="${2:-FF}"
    hex="${hex#\#}"
    echo "rgba(${hex}${alpha})"
}

# Helper: ensure directory exists
ensure_dir(){
    mkdir -p "$(dirname "$1")"
}

# ══════════════════════════════════════════════════════════════════════════════
# WAYBAR THEME
# ══════════════════════════════════════════════════════════════════════════════

generate_waybar(){
    local out="$CONFIG_DIR/waybar/theme-dynamic.css"
    ensure_dir "$out"

    cat > "$out" << EOF
/* MolniOS Waybar Theme - Dynamic Colors */
/* Generated by molnios-templates.sh */
/* DO NOT EDIT - This file is automatically generated */

@define-color background ${background};
@define-color foreground ${foreground};

@define-color color0 ${color0};
@define-color color1 ${color1};
@define-color color2 ${color2};
@define-color color3 ${color3};
@define-color color4 ${color4};
@define-color color5 ${color5};
@define-color color6 ${color6};
@define-color color7 ${color7};
@define-color color8 ${color8};
@define-color color9 ${color9};
@define-color color10 ${color10};
@define-color color11 ${color11};
@define-color color12 ${color12};
@define-color color13 ${color13};
@define-color color14 ${color14};
@define-color color15 ${color15};

/* Semantic colors */
@define-color base ${color0};
@define-color surface0 ${color1};
@define-color surface1 ${color2};
@define-color surface2 ${color3};
@define-color text ${foreground};
@define-color subtext ${color8};

/* Accent colors from palette */
@define-color red ${color1};
@define-color green ${color2};
@define-color yellow ${color3};
@define-color blue ${color4};
@define-color magenta ${color5};
@define-color cyan ${color6};
@define-color lavender ${color13};
@define-color sapphire ${color12};
EOF
}

# ══════════════════════════════════════════════════════════════════════════════
# ROFI THEME
# ══════════════════════════════════════════════════════════════════════════════

generate_rofi(){
    local out="$CONFIG_DIR/rofi/colors-dynamic.rasi"
    ensure_dir "$out"

    cat > "$out" << EOF
/* MolniOS Rofi Theme - Dynamic Colors */
/* Generated by molnios-templates.sh */
/* DO NOT EDIT - This file is automatically generated */

* {
    background:     ${background};
    foreground:     ${foreground};

    color0:         ${color0};
    color1:         ${color1};
    color2:         ${color2};
    color3:         ${color3};
    color4:         ${color4};
    color5:         ${color5};
    color6:         ${color6};
    color7:         ${color7};
    color8:         ${color8};
    color9:         ${color9};
    color10:        ${color10};
    color11:        ${color11};
    color12:        ${color12};
    color13:        ${color13};
    color14:        ${color14};
    color15:        ${color15};

    /* Semantic mappings */
    bg:             ${color0};
    bg-alt:         ${color1};
    fg:             ${foreground};
    fg-alt:         ${color8};

    accent:         ${color4};
    urgent:         ${color1};
    active:         ${color2};

    selected-bg:    ${color4};
    selected-fg:    ${color0};
}
EOF
}

# ══════════════════════════════════════════════════════════════════════════════
# DUNST THEME
# ══════════════════════════════════════════════════════════════════════════════

generate_dunst(){
    local out="$CONFIG_DIR/dunst/dunstrc-dynamic"
    ensure_dir "$out"

    # Calculate transparency versions
    local bg_trans="${color0}1A"  # 10% opacity
    local fg_trans="${foreground}BF"  # 75% opacity

    cat > "$out" << EOF
# MolniOS Dunst Theme - Dynamic Colors
# Generated by molnios-templates.sh
# DO NOT EDIT - This file is automatically generated
# Include this in your main dunstrc with: include = ~/.config/dunst/dunstrc-dynamic

[urgency_low]
background = "${bg_trans}"
foreground = "${fg_trans}"
frame_color = "${color4}"
timeout = 5

[urgency_normal]
background = "${bg_trans}"
foreground = "${foreground}"
frame_color = "${color4}"
timeout = 10

[urgency_critical]
background = "${color1}80"
foreground = "${foreground}"
frame_color = "${color1}"
timeout = 0
EOF
}

# ══════════════════════════════════════════════════════════════════════════════
# SWAYNC THEME
# ══════════════════════════════════════════════════════════════════════════════

generate_swaync(){
    local out="$CONFIG_DIR/swaync/colors-dynamic.css"
    ensure_dir "$out"

    cat > "$out" << EOF
/* MolniOS SwayNC Theme - Dynamic Colors */
/* Generated by molnios-templates.sh */
/* DO NOT EDIT - This file is automatically generated */

:root {
    --background: ${background};
    --foreground: ${foreground};

    --color0: ${color0};
    --color1: ${color1};
    --color2: ${color2};
    --color3: ${color3};
    --color4: ${color4};
    --color5: ${color5};
    --color6: ${color6};
    --color7: ${color7};
    --color8: ${color8};
    --color9: ${color9};
    --color10: ${color10};
    --color11: ${color11};
    --color12: ${color12};
    --color13: ${color13};
    --color14: ${color14};
    --color15: ${color15};

    /* Semantic colors */
    --accent-color: ${color4};
    --notification-color-critical: ${color1}B3;
    --reply-color: ${color12};
}
EOF
}

# ══════════════════════════════════════════════════════════════════════════════
# KITTY THEME
# ══════════════════════════════════════════════════════════════════════════════

generate_kitty(){
    local out="$CONFIG_DIR/kitty/colors-dynamic.conf"
    ensure_dir "$out"

    cat > "$out" << EOF
# MolniOS Kitty Theme - Dynamic Colors
# Generated by molnios-templates.sh
# DO NOT EDIT - This file is automatically generated

foreground ${foreground}
background ${background}
cursor ${cursor}
cursor_text_color ${background}

# Selection
selection_foreground ${background}
selection_background ${color4}

# URL
url_color ${color12}

# Black
color0 ${color0}
color8 ${color8}

# Red
color1 ${color1}
color9 ${color9}

# Green
color2 ${color2}
color10 ${color10}

# Yellow
color3 ${color3}
color11 ${color11}

# Blue
color4 ${color4}
color12 ${color12}

# Magenta
color5 ${color5}
color13 ${color13}

# Cyan
color6 ${color6}
color14 ${color14}

# White
color7 ${color7}
color15 ${color15}

# Tab colors
active_tab_foreground ${background}
active_tab_background ${color4}
inactive_tab_foreground ${foreground}
inactive_tab_background ${color1}

# Border colors
active_border_color ${color4}
inactive_border_color ${color8}
EOF
}

# ══════════════════════════════════════════════════════════════════════════════
# GTK CSS (for libadwaita apps)
# ══════════════════════════════════════════════════════════════════════════════

generate_gtk(){
    local gtk3_out="$CONFIG_DIR/gtk-3.0/colors-dynamic.css"
    local gtk4_out="$CONFIG_DIR/gtk-4.0/colors-dynamic.css"

    ensure_dir "$gtk3_out"
    ensure_dir "$gtk4_out"

    local content
    content=$(cat << EOF
/* MolniOS GTK Theme - Dynamic Colors */
/* Generated by molnios-templates.sh */
/* DO NOT EDIT - This file is automatically generated */

@define-color theme_bg_color ${background};
@define-color theme_fg_color ${foreground};
@define-color theme_base_color ${color0};
@define-color theme_text_color ${foreground};
@define-color theme_selected_bg_color ${color4};
@define-color theme_selected_fg_color ${background};

@define-color accent_color ${color4};
@define-color accent_bg_color ${color4};
@define-color accent_fg_color ${background};

@define-color destructive_color ${color1};
@define-color destructive_bg_color ${color1};
@define-color destructive_fg_color ${background};

@define-color success_color ${color2};
@define-color success_bg_color ${color2};
@define-color success_fg_color ${background};

@define-color warning_color ${color3};
@define-color warning_bg_color ${color3};
@define-color warning_fg_color ${background};

@define-color error_color ${color1};
@define-color error_bg_color ${color1};
@define-color error_fg_color ${background};

@define-color window_bg_color ${background};
@define-color window_fg_color ${foreground};
@define-color view_bg_color ${color0};
@define-color view_fg_color ${foreground};

@define-color headerbar_bg_color ${color1};
@define-color headerbar_fg_color ${foreground};
@define-color headerbar_backdrop_color ${color0};

@define-color popover_bg_color ${color1};
@define-color popover_fg_color ${foreground};

@define-color card_bg_color ${color1};
@define-color card_fg_color ${foreground};

@define-color dialog_bg_color ${color1};
@define-color dialog_fg_color ${foreground};
EOF
)

    echo "$content" > "$gtk3_out"
    echo "$content" > "$gtk4_out"
}

# ══════════════════════════════════════════════════════════════════════════════
# ZSH/FISH color exports
# ══════════════════════════════════════════════════════════════════════════════

generate_shell_exports(){
    # These are already generated by pywal/wallust/matugen
    # We just ensure they exist in the expected location

    if [[ -f "$CACHE_DIR/wal/colors.sh" ]];then
        # Already generated by backend
        :
    fi

    if [[ -f "$CACHE_DIR/wal/colors.fish" ]];then
        # Already generated by backend
        :
    fi
}

# ══════════════════════════════════════════════════════════════════════════════
# Execute all generators
# ══════════════════════════════════════════════════════════════════════════════

generate_waybar
generate_rofi
generate_dunst
generate_swaync
generate_kitty
generate_gtk
generate_shell_exports

exit 0
