# Use if you have bad contrast value.
# check_contrast = true
saturation = 50

[entry]
template = 'vim'
target = '~/.cache/wal/colors.vim'

[templates]
pywal = { src = "templates/", dst = "~/.cache/wal/", pywal = true }