#!/index/bin/env sh

# Pywal-compatible fallback variables generated by Matugen
wal_color0="{{base16_00_hex}}"
wal_color1="{{base16_01_hex}}"
wal_color2="{{base16_02_hex}}"
wal_color3="{{base16_03_hex}}"
wal_color4="{{base16_04_hex}}"
wal_color5="{{base16_05_hex}}"
wal_color6="{{base16_06_hex}}"
wal_color7="{{base16_07_hex}}"
wal_color8="{{base16_08_hex}}"
wal_color9="{{base16_09_hex}}"
wal_color10="{{base16_10_hex}}"
wal_color11="{{base16_11_hex}}"
wal_color12="{{base16_12_hex}}"
wal_color13="{{base16_13_hex}}"
wal_color14="{{base16_14_hex}}"
wal_color15="{{base16_15_hex}}"

# Core background/foreground roles
background="{{base16_00_hex}}"
foreground="{{base16_05_hex}}"
cursor="{{base16_06_hex}}"