[mgr]
sort_by        = "extension" # size
linemode       = "size" # Can't show folder sizes if sort_by!=size
show_hidden    = true

[preview]
wrap            = "yes"
image_filter    = "lanczos3"
image_quality   = 60

[tasks]
file_workers     = 10
plugin_workers   = 10
fetch_workers    = 10
preload_workers  = 10
process_workers  = 10
image_alloc      = 268435456 # 256MB
image_bound      = [ 5000, 5000 ]

[input]
cursor_blink = true

[confirm]
trash_title 	= "Remove {n} selected file{s}?"
